baseURL = 'https://setyahafit.space/'
languageCode = 'id-id'
title = 'Setya Hafit | Cybersecurity Consultant'
theme = 'PaperMod'
enableRobotsTXT = true  # Agar Google boleh meng-crawl website

[params]
    # --- Tampilan & Warna ---
    defaultTheme = "dark" 
    
    # --- Footer Profesional (White Labeling) ---
    # Mematikan tulisan "Powered by Hugo" agar terlihat pro
    showFooterPoweredBy = false
    # Copyright custom ala konsultan
    copyright = "Â© 2025 Setya Hafit | Securing the Digital Space"

    # --- SEO Metadata ---
    author = "Setya Hafit"
    description = "Portfolio Setya Hafit: Cybersecurity Analyst, DevSecOps, dan Network Security Specialist."
    keywords = ["Setya Hafit", "Cybersecurity Indonesia", "Jasa Pentest", "DevSecOps", "Writeups", "CTF"]
    
    # --- VERIFIKASI GOOGLE (SUDAH DIPERBAIKI) ---
    # Cukup masukkan kode hash uniknya saja. 
    # (Saya sudah hapus awalan 'google-site-verification=' agar formatnya valid)
    googleSiteVerification = "hS42OPdnna2aUl9vx_isuYUjZPj0auXP93pzDp2wqc0"

    # --- Pengaturan Umum ---
    DateFormat = "2 January 2006"
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true # Tombol copy di kotak kodingan

# --- Konfigurasi Profil Halaman Depan ---
[params.profileMode]
    enabled = true
    title = "Setya Hafit"
    subtitle = "Cybersecurity Enthusiast | DevSecOps Learner"
    imageUrl = "me.jpg"
    imageWidth = 150
    imageHeight = 150
    
    # Tombol Sosial Media
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/setyahafitp"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/setya-hafit-pambudi-0b6327237/"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:email-anda@gmail.com" # JANGAN LUPA: Ganti dengan email asli Anda di sini

# --- Konfigurasi Favicon (Ikon Tab Browser) ---
[params.assets]
    favicon = "me.jpg"
    favicon16x16 = "me.jpg"
    favicon32x32 = "me.jpg"
    apple_touch_icon = "me.jpg"
    safari_pinned_tab = "me.jpg"

# --- Pengaturan Output untuk Search ---
[outputs]
    home = ["HTML", "RSS", "JSON"]

# --- Konfigurasi Menu Navigasi (Mobile Friendly) ---
[menu]
    # 1. Menu About
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10

    # 2. Menu Jurnal
    [[menu.main]]
        identifier = "posts"
        name = "Jurnal"
        url = "/posts/"
        weight = 20

    # 3. Menu Contact (PGP)
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 30

    # 4. Menu Search
    [[menu.main]]
        identifier = "search"
        name = "Search"
        url = "/search/"
        weight = 40