baseURL = 'https://setyahafit.space/'
languageCode = 'id-id'
title = 'Setya Hafit | Cybersecurity'
theme = 'PaperMod'

[params]
    defaultTheme = "dark" # Default mode gelap (khas hacker/dev)
    description = "Portfolio dan Jurnal Cybersecurity Setya Hafit"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Jurnal"
    url = "/posts/"
    weight = 20

# --- Konfigurasi Profil Halaman Depan ---
[params.profileMode]
    enabled = true
    title = "Setya Hafit"
    subtitle = "Cybersecurity Enthusiast | DevSecOps Learner"
    imageUrl = "me.jpg"       # Ini otomatis mengambil dari folder static
    imageWidth = 150
    imageHeight = 150
    
    # Tombol Sosial Media (Bisa diedit nanti)
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/setyahafitp"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/setya-hafit-pambudi-0b6327237/"

# --- Pengaturan Output untuk Search ---
[outputs]
    home = ["HTML", "RSS", "JSON"] # JSON wajib ada untuk fitur Search

# --- Konfigurasi Menu Navigasi ---
[[menu.main]]
    identifier = "archives"
    name = "Archive"
    url = "/archives/"
    weight = 10

[[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 20

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

    # --- Konfigurasi Favicon (Icon Tab Browser) ---
[params.assets]
    favicon = "me.jpg"
    favicon16x16 = "me.jpg"
    favicon32x32 = "me.jpg"
    apple_touch_icon = "me.jpg"
    safari_pinned_tab = "me.jpg"