baseURL = 'https://setyahafit.space/'
languageCode = 'id-id'
title = 'Setya Hafit'  # <-- Cuma Nama Saja (Biar Rapi di HP)
theme = 'PaperMod'
enableRobotsTXT = true

[params]
    defaultTheme = "dark"
    
    # --- SEO Metadata ---
    author = "Setya Hafit"
    description = "Jurnal belajar dan catatan sertifikasi Google Cybersecurity Setya Hafit."
    keywords = ["Setya Hafit", "Cybersecurity", "Google Cybersecurity", "Blog", "Jurnal"]
    
    # --- Verifikasi Google ---
    googleSiteVerification = "hS42OPdnna2aUl9vx_isuYUjZPj0auXP93pzDp2wqc0"

    # --- Pengaturan UI ---
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    
    # Kita matikan footer bawaan tema di sini (tapi nanti kita timpa pakai file HTML biar yakin)
    showFooterPoweredBy = false
    copyright = "Â© 2025 Setya Hafit"

# --- Profil Halaman Depan ---
[params.profileMode]
    enabled = true
    title = "Setya Hafit"
    # Subtitle yang lebih rendah hati & sesuai tujuan blog
    subtitle = "Google Cybersecurity Certification Journey | Learning & Sharing"
    imageUrl = "me.jpg"
    imageWidth = 150
    imageHeight = 150
    
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/setyahafitp"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/setya-hafit-pambudi-0b6327237/"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:setya@gmail.com" # Ganti email asli

[params.assets]
    favicon = "me.jpg"
    favicon16x16 = "me.jpg"
    favicon32x32 = "me.jpg"
    apple_touch_icon = "me.jpg"
    safari_pinned_tab = "me.jpg"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    [[menu.main]]
        identifier = "posts"
        name = "Jurnal"
        url = "/posts/"
        weight = 20
    [[menu.main]]
        identifier = "credentials"
        name = "Credentials"
        url = "/credentials/"
        weight = 25  # Angka 25 agar posisinya pas di tengah    
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 30
    [[menu.main]]
        identifier = "search"
        name = "Search"
        url = "/search/"
        weight = 40