baseURL = 'https://setyahafit.space/'
languageCode = 'id-id'
title = 'Setya Hafit | Cybersecurity'
theme = 'PaperMod'

[params]
    defaultTheme = "dark" # Default mode gelap (khas hacker/dev)
    description = "Portfolio dan Jurnal Cybersecurity Setya Hafit"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Jurnal"
    url = "/posts/"
    weight = 20
    
# --- Konfigurasi Profil Halaman Depan ---
[params.profileMode]
    enabled = true
    title = "Setya Hafit"
    subtitle = "Cybersecurity Enthusiast | DevSecOps Learner"
    imageUrl = "me.jpg"       # Ini otomatis mengambil dari folder static
    imageWidth = 150
    imageHeight = 150
    
    # Tombol Sosial Media (Bisa diedit nanti)
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/setyahafitp"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/username-anda"